spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders_book?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka

