spring:
  datasource:
    url: jdbc:mysql://${MYSQL:localhost:3306}/orders_book?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8777}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8070/eureka}





customers:
  default:
    tva: 1010
    coupon: 10001